#if !canImport(ObjectiveC)
import XCTest

extension InfoHashTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InfoHashTests = [
        ("testDistance", testDistance),
        ("testInit_Comparable", testInit_Comparable),
        ("testInit_Data", testInit_Data),
        ("testInit_Normal", testInit_Normal),
        ("testInit_Not20Bytes", testInit_Not20Bytes),
        ("testMiddlePoint", testMiddlePoint),
        ("testPrev", testPrev),
    ]
}

extension MetainfoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MetainfoTests = [
        ("testDecode_UbuntuMetainfo", testDecode_UbuntuMetainfo),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(InfoHashTests.__allTests__InfoHashTests),
        testCase(MetainfoTests.__allTests__MetainfoTests),
    ]
}
#endif
